### ISSUE TITLE
For Luciano

### ISSUE THREAD

**Issue by TheTechTravis** [LucianoChilean/CrudUsuarios#1]
@LucianoChilean Hey man, I couldn’t find any other way to contact you. If you see this please go to my profile page. My email is linked there. I am the guy who used to play StarCraft 2 and help you improve with your English years ago. I’d love to get in touch with you again.

**Comment by LucianoChilean** [comment]
Hey dude. I remember you, yeah you help me to pratice my english. If u want dude u can send me your phone number to my email: mattensohn64@gmail.com. and then we can speak dude.
